const SAMPLE_RATE = 16000

module.exports = {
	SHOW_TIMINGS: false,
	THRESHOLD: 0.5,
	DTW_REF: 0.24,
	BAND_SIZE: 4,
	PREEMPHASIS_COEFFICIENT: 0.97,
	// RAW_ENERGY: true,
	// NUM_MEL_BINS: 12,
	// NUM_FEATURES: 12,
	FRAME_LENGTH_MS: 25.0,
	FRAME_SHIFT_MS: 10.0,
	SAMPLE_RATE,
	// LOW_FREQ: 20,
	// HIGH_FREQ: SAMPLE_RATE / 2
}